-- PostgreSQL Dog Data Script
CREATE TABLE dogs (
    id SERIAL PRIMARY KEY,
    name VARCHAR(50),
    breed VARCHAR(50),
    description TEXT
);

INSERT INTO dogs (id, name, breed, description) VALUES
('Labrin', 'Labrador Retriever', 'Friendly, loyal, and great with kids. Labs are playful family dogs and usually welcoming to strangers.'),
('Labbie', 'Labrador Retriever', 'Highly social and affectionate. Known for patience with children and friendliness toward everyone.'),
('Labra', 'Labrador Retriever', 'Easygoing and energetic. Excellent family dog that enjoys outdoor play and meeting new people.'),
('Goldie', 'Golden Retriever', 'Gentle, patient, and trustworthy. Great with families and kind to guests and strangers alike.'),
('Goldor', 'Golden Retriever', 'Warm and loving personality. Very tolerant with kids and enjoys social activities.'),
('Golda', 'Golden Retriever', 'Smart and loyal. Always eager to please, thrives in family settings.'),
('Shepby', 'German Shepherd', 'Protective and confident. Loyal to family, can be reserved with strangers unless socialized early.'),
('Germy', 'German Shepherd', 'Highly intelligent and obedient. Excellent family protector and affectionate once trust is built.'),
('Sheppy', 'German Shepherd', 'Faithful and energetic. Enjoys structure and is loyal to family members.'),
('Beagsy', 'Beagle', 'Curious and cheerful. Excellent with children and usually friendly toward other dogs and people.'),
('Beagor', 'Beagle', 'Playful and gentle. Known for a social and outgoing nature with families and friends.'),
('Beagie', 'Beagle', 'Happy-go-lucky temperament. Loves group play and family activities.'),
('Husko', 'Siberian Husky', 'Energetic and independent. Friendly with families but needs supervision with small pets.'),
('Huskey', 'Siberian Husky', 'Outgoing and playful. Enjoys human company but can be stubborn without firm guidance.'),
('Sibra', 'Siberian Husky', 'Sociable and adventurous. Good with active families, friendly toward other dogs.'),
('Boxen', 'Boxer', 'Lively, loyal, and affectionate. Great playmate for children and protective of loved ones.'),
('Boxy', 'Boxer', 'Energetic and gentle with kids. Thrives in family environments and social gatherings.'),
('Rottie', 'Rottweiler', 'Calm and confident. Devoted to family, may be aloof with strangers until introduced.'),
('Rottor', 'Rottweiler', 'Protective yet affectionate. Excellent guard dog that bonds deeply with family.'),
('Rotto', 'Rottweiler', 'Steady and loyal temperament. Best with consistent training and socialization.'),
('Dobsy', 'Doberman Pinscher', 'Alert and loyal. Bonds closely with family, reserved around new people.'),
('Dober', 'Doberman Pinscher', 'Intelligent and fearless. Gentle with family and children when well-trained.'),
('Dobby', 'Doberman Pinscher', 'Affectionate and brave. Thrives on companionship and structure.'),
('Pitty', 'American Pit Bull Terrier', 'Affectionate and energetic. Great with children when socialized; very people-oriented.'),
('Pitor', 'American Pit Bull Terrier', 'Loving and playful. Misunderstood breed known for loyalty and friendliness.'),
('Pibby', 'American Pit Bull Terrier', 'Outgoing and gentle. Bonds strongly with humans and thrives in active families.'),
('Bullsy', 'Bulldog', 'Gentle and loving. Calm indoors and affectionate with children and family.'),
('Bullo', 'Bulldog', 'Steady and loyal. Adapts well to home life and enjoys human contact.'),
('Bully', 'Bulldog', 'Patient and kind. Excellent companion for children and apartment living.'),
('Puggo', 'Pug', 'Comical and affectionate. Loves everyone, including kids and strangers.'),
('Puggie', 'Pug', 'Friendly and charming. Ideal for families seeking a social lapdog.'),
('Chihko', 'Chihuahua', 'Lively and alert. Loyal to owners but can be shy around unfamiliar people.'),
('Chihny', 'Chihuahua', 'Devoted companion. Great for single owners, cautious around strangers.'),
('Chihra', 'Chihuahua', 'Bold and curious. Loves attention but may bark at new faces.'),
('Dachie', 'Dachshund', 'Clever and curious. Good with older children, cautious with strangers.'),
('Daxie', 'Dachshund', 'Playful and affectionate. Bonds closely with family but can be vocal.'),
('Dachor', 'Dachshund', 'Fearless personality. Sociable when introduced properly to others.'),
('Sheltor', 'Shetland Sheepdog', 'Gentle, obedient, and sensitive. Excellent family companion, polite with strangers.'),
('Sheltie', 'Shetland Sheepdog', 'Loving and alert. Great with kids and enjoys quiet home life.'),
('Shiba', 'Shiba Inu', 'Independent and proud. Affectionate with family, reserved with strangers.'),
('Shibra', 'Shiba Inu', 'Curious and clean. Enjoys family time but prefers respectful social contact.'),
('Shibko', 'Shiba Inu', 'Playful yet self-reliant. Loyal to owners, polite when socialized.'),
('Corgy', 'Pembroke Welsh Corgi', 'Alert and affectionate. Great with children and other pets.'),
('Corby', 'Pembroke Welsh Corgi', 'Cheerful and loyal. Excellent family companion, enjoys social activities.'),
('Corgor', 'Pembroke Welsh Corgi', 'Smart and loving. Gets along well with kids and new people.'),
('Dalmy', 'Dalmatian', 'Energetic and social. Loves attention and playtime with family.'),
('Dalor', 'Dalmatian', 'Friendly and active. Great jogging partner and family dog.'),
('Dalsy', 'Dalmatian', 'Outgoing and lively. Enjoys human company and outdoor activities.'),
('Pooma', 'Poodle', 'Intelligent and elegant. Gentle with children and friendly to guests.'),
('Poodie', 'Poodle', 'Highly trainable and loyal. Excellent social manners and affectionate.'),
('Poofy', 'Poodle', 'Playful and kind. Fits well in homes with other pets and kids.'),
('Maltie', 'Maltese', 'Sweet-natured and affectionate. Loves family life and gentle social play.'),
('Malty', 'Maltese', 'Lively and loving. Thrives on companionship and friendly visitors.'),
('Shihra', 'Shih Tzu', 'Affectionate lapdog. Excellent with kids, enjoys social attention.'),
('Shiho', 'Shih Tzu', 'Gentle and cheerful. Adapts well to family homes and visitors.'),
('Tzumi', 'Shih Tzu', 'Calm and loyal. Bonds closely with family, friendly with others.'),
('Yorby', 'Yorkshire Terrier', 'Brave and affectionate. Playful with children and outgoing with people.'),
('Yorko', 'Yorkshire Terrier', 'Energetic and curious. Loves being around family and new friends.'),
('Yorkie', 'Yorkshire Terrier', 'Confident and devoted. Excellent companion and alert watchdog.'),
('Aussie', 'Australian Shepherd', 'Smart and active. Great with kids, thrives in social and outdoor settings.'),
('Auzzy', 'Australian Shepherd', 'Energetic and loyal. Excellent family partner and friendly with strangers.'),
('Ausher', 'Australian Shepherd', 'Protective but kind. Loves children and teamwork play.'),
('Greyra', 'Greyhound', 'Gentle and quiet. Calm indoors, friendly to children and new faces.'),
('Greyo', 'Greyhound', 'Elegant and sweet. Enjoys peaceful family environments and outdoor walks.'),
('Greyby', 'Greyhound', 'Affectionate and calm. Gets along easily with people and pets.'),
('Sammy', 'Samoyed', 'Friendly and smiling personality. Excellent with children and very sociable.'),
('Samo', 'Samoyed', 'Playful and affectionate. Loves meeting new people and being part of a group.'),
('Samra', 'Samoyed', 'Gentle and fluffy companion. Great with families and strangers alike.'),
('Basen', 'Basenji', 'Independent and quiet. Loyal to family, reserved with outsiders.'),
('Basa', 'Basenji', 'Curious and intelligent. Good with children when well-socialized.'),
('Basy', 'Basenji', 'Alert and clean. Affectionate but cautious with strangers.'),
('Akira', 'Akita', 'Dignified and loyal. Deeply devoted to family, protective of home.'),
('Akko', 'Akita', 'Calm and confident. Gentle with children, wary of strangers.'),
('Akitty', 'Akita', 'Strong and quiet. Loyal to owners, best with early socialization.'),
('Whippy', 'Whippet', 'Gentle and affectionate. Great with kids and social with visitors.'),
('Whippo', 'Whippet', 'Quiet and loving. Enjoys lounging indoors and playing outdoors.'),
('Whipra', 'Whippet', 'Mild and loyal. Good with families and pets, polite with strangers.'),
('Colla', 'Border Collie', 'Highly intelligent and energetic. Great with active families, friendly but focused.'),
('Colly', 'Border Collie', 'Eager to please and loyal. Bonds deeply with family members.'),
('Collor', 'Border Collie', 'Smart and sociable. Loves kids and group activities.'),
('Newfy', 'Newfoundland', 'Gentle giant. Exceptionally kind with children and calm in social settings.'),
('Newlo', 'Newfoundland', 'Patient and protective. Excellent family dog, friendly to everyone.'),
('Newra', 'Newfoundland', 'Loving and serene. Devoted companion with a gentle heart.'),
('Greato', 'Great Dane', 'Affectionate and noble. Wonderful with kids and visitors.'),
('Dano', 'Great Dane', 'Gentle and loyal. Despite size, very friendly and easygoing.'),
('Danzy', 'Great Dane', 'Playful and calm. Loves family time and social greetings.'),
('Sainto', 'Saint Bernard', 'Gentle and caring. Great with children, polite and calm around strangers.'),
('Bernie', 'Saint Bernard', 'Loyal and patient. A big-hearted family protector.'),
('Sainty', 'Saint Bernard', 'Kind and dependable. Friendly toward guests and very nurturing.'),
('Cavvy', 'Cavalier King Charles Spaniel', 'Affectionate and gentle. Wonderful with children and strangers alike.'),
('Cavro', 'Cavalier King Charles Spaniel', 'Sociable and cheerful. Adapts well to family life and outings.'),
('Cavie', 'Cavalier King Charles Spaniel', 'Loving and loyal. Gets along easily with everyone.'),
('Papra', 'Papillon', 'Smart and lively. Friendly with kids and enjoys new people.'),
('Pappy', 'Papillon', 'Playful and social. Excellent companion and quick learner.'),
('Paplo', 'Papillon', 'Charming and alert. Loves family attention and social visits.'),
('Vizra', 'Vizsla', 'Energetic and affectionate. Bonds deeply with family, loves meeting new people.'),
('Vizzo', 'Vizsla', 'Loyal and spirited. Excellent with children and outdoor activities.'),
('Vizza', 'Vizsla', 'Gentle and loving. Great with families and sociable environments.'),
('Weimy', 'Weimaraner', 'Friendly and energetic. Loyal to family, enjoys active lifestyles.'),
('Weimo', 'Weimaraner', 'Bold and affectionate. Great with kids and thrives on attention.'),
('Weimra', 'Weimaraner', 'Athletic and loyal. Very people-oriented and social.'),
('Pointer', 'Pointer', 'Friendly and eager. Loves outdoor activities and being around people.'),
('Pointo', 'Pointer', 'Confident and kind. Excellent with families and social play.'),
('Pointy', 'Pointer', 'Energetic and affectionate. Gets along easily with everyone.');
